### ISSUE TITLE
Slot should consist of `slot_granularity` number of blocks

### ISSUE THREAD

**Issue by NinoLipartiia** [CronCats/cw-croncat#138]
In current implementation a new slot is created for every block and `slot_granularity` parameter isn't used.

I think we need to implement something similar to this:
https://github.com/CronCats/contracts/blob/cafd3caafb91b45abb6e811ce0fa2819980d6f96/manager/src/lib.rs#L166-L187

**Comment by mikedotexe** [comment]
Good catch, thanks

**Comment by TrevorJTClarke** [comment]
Noting that the granularity really only applies to timestamps, as we accept blocks to the single block. ordered map on blocks is ideal, where timestamps need slot/range because timestamps spread inter-block.
Previous slot granularity was 60 seconds, because the guarantee was within a minute on near. However, we want to get to a slot granularity of ~10seconds or equal to the chains block time duration.
