### ISSUE TITLE
[CW-CRONCAT] Insertable tasks action messages

### ISSUE THREAD

**Issue by Buckram123** [CronCats/cw-croncat#189]
We can take the last result from the `rules` response and replace some placeholder inside our messages.
Example: 
rules: 
```
[
- Admin of X contract != Z
- Check who admin of `addr` contract
]
End result -> new_admin `addr`
```
Now insert inside our action
```
- Send 10 croncat coins to the `RULES_RESULT_PLACEHOLDER` // where placeholder replaced by the new `admin_addr`
```
Hey @TrevorJTClarke! We can do multiple rules results insertion, need your opinion here, for this example it would be:
Insert second(idx) result inside our action
```
- Send 10 croncat coins to the `RULES_RESULT_PLACEHOLDER1` // where placeholder1 replaced by the new `admin_addr`
```

**Comment by mikedotexe** [comment]
This is seriously so exciting

**Comment by gandolfoni** [comment]
Can't wait. CronCat is going to set a high bar when it comes to other dapps throughout the interchain. One of the few projects that gives me hope we aren't just going to be stuck fooling around with eth defi forks from 3 years ago. Except with a cool space theme.

**Comment by Buckram123** [comment]
Another way of doing insertable messages, would be replacing a `value` found from list of `key`'s inside `action[]`
Adding a new optional field in the task creation struct
```rust
TaskRequest {
    // ...
    pub actions: Vec<Action>,
    pub rules: Option<Vec<Rule>>,
    // maybe
    // customizable_action(s?): Option<Action>, 
    // ...
    pub replace_action_value_by_rule_res: Option<Vec<ValueIndex>>,
}
```
example:
```bash
BASE64_TRANSFER=$(echo -b '{"transfer":{"recipient":"bob","amount":"5"}}' | base64) # with current approach: {"transfer":{"recipient":$r_r,"amount":"5"}}
"actions": [
                {
                    "msg": {
                        "wasm": {
                            "execute": {
                                "contract_addr": "juno123",
                                "msg": "'$BASE64_TRANSFER'",
                                "funds": []
                            }
                        }
                    },
                    "gas_limit": null
                }
            ],
"replace_action_value_by_rule_res": [0, "msg", "wasm", "execute", "msg", "transfer", "recipient"]
```
Notice that keys "transfer" and "recipient" is a part of binary message.

End result would be that "bob" replaced to the rules response.
@TrevorJTClarke, need your thoughts on this approach!

**Comment by TrevorJTClarke** [comment]
I like the `replace_action_value_by_rule_res` tree - I'm still thinking further on this, how it works from integrations realistically. For example, this actually feels brittle when there are multiple (potentially overriding) variables

I do want to note - i think im going to stick with the current Rule boolean checking:
**Rule boolean evaluation should cascade, and never branch.**
So this topic only addresses the optional rule response data and how it gets used in Actions.

I think the following scenarios should offer us a good approach to start with:

Use Cases:
1. Buy/mint NFT, add new NFT owner to DAO via creating new proposal
2. Claim staking rewards weekly, has balance GTE 10 $OSMO, Check prices, DCA $OSMO to $JUNO on junoswap
3. Escrow arbitration, condition met between a window of time

This leads to scenario types:
1. **Cascading Rules:** Rules supplement sequentially to "next" rules, with the last rule returning a variable payload available to Actions. 
2. **Collector Rules:** Rules are checked sequentially, but offer addressable variables within Actions, since keys can collide, the variables are stored in rule index order and can be addressed by index from an Action
3. **Mutation Rules:** Rules are sequentially able to modify previous bucket of variables (think of a json object, thats k/v store can mutate based on previous responses), then the object is available to replace arguments (k/v) for key matches within Action msg

My personal feelings are that #2 is the way to go (pretty sure this is the type you thought of anyway). I want to document the avenues we _could_ go, so we know pros/cons of each approach.

SO, Pros/Cons of each type:
1. Pro: Simpler logic path & complexity. Con: Limited to last variables from rules, could limit future options.
2. Pro: Extreme flexibility for Actions. Pro: Isolates output via index. Con: 
3. Pro: Simplifies data variable scope. Con: Feels like security attack surface is large - thinking of ways that a malicious rule in the stack becomes a problem for overriding other k/v.


So here's pseudo code for scenario #2, use case #2:

```
# Task: happens weekly, using task balance until gone.

# Rule 1:
Input: { "has_balance_gte": { "address": "juno...", "required_balance": { "amount": "10000000", "denom": "uosmo" } } }
Output: { "response": true, "data": {} }

# Rule 2:
Input: { "token1_for_token2_price": { "token1_amount": "1000000" } }
Output: { "response": true, "data": { "token2_amount": "870000" } }

# Action 1:
Variables needed: N/A
msg: { "distribution": { "withdraw_delegator_reward": { "validator": "junovaloper..." } } }


# Action 2:
Variables needed: "min_output"
msg: {
  swap {
    "input_token": "osmo",
    "input_amount": "1000000",
    "min_output": ""
  }
}
```

This kinda brings up the need for **"transforms"**, which essentially are describing how mappings of replacements happen.
The only other solution is (a very inflexible version) what i had previously thought, which is something like only replacing they whole `msg` with whatever the last rule output had generated, forcing developer to implement ahead of time.

So a **transform** could look like what you thought, however I propose:

```
# Key is the action path, Value is the rule variable to replace within action - using indexed response.
"transforms": {
  "swap.min_output": [1, "token2_amount"]
}
```

I also could see it a diff way:
```
# Same K/V setup as above
# transforms are action index based
"transforms": [
  {},
  {
    "swap.min_output": [1, "token2_amount"]
  }
]
```

NOTE: I believe we can remove "msg.wasm.execute" as we can have a matcher that dives into the correct context for each CosmosSDK msg type.


Brutal honest thoughts only requested :D


### Final Note
We must keep in mind how both user (web UI) and SDK will interact with this. The right implementation should offer flexibility to the user, but also non-ambiguity for a contract. A contract should not have to understand the inner workings of variable replacement for rules. Contracts will ultimately be able to integrate the SDK for creating & managing tasks, however complex we allow.

CC @Buckram123 && @mikedotexe

**Comment by TrevorJTClarke** [comment]
After team discussion, here's the agreed upon approach & example:

We will move forward with **Collector Rules**, and add a new **transforms** ability to tasks.

Transforms allow both user and contract to specify how actions consume variables.

Order of Operations:
1. Rules: Cascading variable gleaning
2. Transforms: Index based variable swapping on actions
3. Actions: Index based execution

NOTE: Rules could actually support a simple query, which would have a default boolean value of TRUE. This would allow dynamic query to supplement the transform stack without adding a separate static query complexity.

So a rule response would look like:
```
RuleResponse {
 result: bool
 data: "STUFF"
}
```
OR 
```
RuleResponse "STUFF"
```
But the important part is that the indexed result ends up in transform stack.


```
{
  "create_task": {
    "task": {
      "interval": {
        "Block": 15
      },
      "boundary": null,
      "cw20_coins": [],
      "stop_on_fail": false,
      // Update!
      // bring back https://github.com/CronCats/cw-croncat/blob/main/packages/cw-croncat-core/src/types.rs#L143-L153
      // 
      "rules": [
        {
          // "chain_id": "", // optional, likely need to extend this for ICQ (interchain queries)
          "contract_addr": "",
          "msg": ""
        }
      ],
      // NEW! however, not part of this issue/PR - stubbing as example for full Task context
      "queries": [
        {
          "contract_addr": "",
          "msg": ""
        }
      ],
      // NEW!
      // Transforms are index based values, added by each 
      "transforms": [
        {}, // default, nothing returned, nothing to replace
        // example of how an arbitrary response maps to action field, no deserialization
        {
          "swap.min_output": [ // field path within action
            0, // Action index
          ]
        }
        // example of how a deserialized field from response gets replaces in a key/value position
        {
          "swap.min_output": [ // field path within action
            0, // Action index
            "token2_amount" // field key within response
          ]
        }
      ]
      // No change to Actions
      "actions": [
        {
          "msg": {
            "bank": {
              "send": {
                "amount": [
                  {
                    "amount": "1",
                    "denom": "ujunox"
                  }
                ],
                "to_address": "juno1yhqft6d2msmzpugdjtawsgdlwvgq3samrm5wrw"
              }
            }
          },
          "gas_limit": "1000000"
        }
      ],
    }
  }
}
```

**Comment by TrevorJTClarke** [comment]
@Buckram123 i realized yet another thing to consider:
transforms for rules???

What if i want to have the first rule's response become part of the variable for second rule?
Could we utilize transforms for both rules & actions if available?

**Comment by Buckram123** [comment]
> What if i want to have the first rule's response become part of the variable for second rule? 

That's similar to how stacking rules implemented rn, but the limitation is "stacking rule" will only return last result, or we want it to be able to insert "rule response" into any rule type

**Comment by TrevorJTClarke** [comment]
This was merged!
