### ISSUE TITLE
[NOT MVP] Improve `stop_on_fail`

### ISSUE THREAD

**Issue by Buckram123** [CronCats/cw-croncat#93]
We can give more options when user wants to stop his task
```rust
enum StopOn {
    Failure,
    Event(String),
    Data(Binary),
    Attribute {
        /// In case event type matters
        ty: Option<String>,
        attribute: Attribute,
        /// Actually we can even check if attribute value `<` `<=`...
    },
}
```

**Comment by deveusss** [comment]
Give more description or lets close it @Buckram123 :)

**Comment by Buckram123** [comment]
> Give more description on this or lets close it @Buckram123 :)

Just more options for stopping task reschedule. It's only in 💡 idea💡 state

**Comment by deveusss** [comment]
enum options seem complete to me

**Comment by TrevorJTClarke** [comment]
@Buckram123 @deveusss i really really like the ideas here -- so it annoys me what im about to say:
Can we archive this until users ask?
I actually was on the fence about this one a year ago, and never needed it. There are also further security implications needing considering, since this actually complicates the task lifetime. 
Let's archive for now, and revamp when its needed.
